import { User, UserLocation, Incident } from '@/types';

// Mock incident data for demonstration
export const mockIncidents: Incident[] = [
    {
        id: '1',
        user_id: 'user1',
        type: 'robbery',
        severity: 'high',
        title: 'Armed Robbery at Lekki',
        description: 'Armed robbery reported near Lekki Phase 1 roundabout',
        latitude: 6.4474,
        longitude: 3.4700,
        address: 'Lekki Phase 1, Lagos',
        verified: true,
        anonymous: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        user_id: 'user2',
        type: 'accident',
        severity: 'medium',
        title: 'Traffic Accident on Third Mainland Bridge',
        description: 'Multiple vehicle collision causing traffic',
        latitude: 6.4698,
        longitude: 3.3852,
        address: 'Third Mainland Bridge, Lagos',
        verified: true,
        anonymous: false,
        created_at: new Date(Date.now() - 3600000).toISOString(),
        updated_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '3',
        user_id: 'user3',
        type: 'suspicious_activity',
        severity: 'low',
        title: 'Suspicious Activity in Victoria Island',
        description: 'Suspicious individuals loitering near Eko Hotel',
        latitude: 6.4281,
        longitude: 3.4219,
        address: 'Victoria Island, Lagos',
        verified: false,
        anonymous: true,
        created_at: new Date(Date.now() - 7200000).toISOString(),
        updated_at: new Date(Date.now() - 7200000).toISOString(),
    },
    {
        id: '4',
        user_id: 'user4',
        type: 'kidnapping',
        severity: 'critical',
        title: 'Attempted Kidnapping in Ajah',
        description: 'Attempted kidnapping of a child near Ajah market',
        latitude: 6.4672,
        longitude: 3.5663,
        address: 'Ajah, Lagos',
        verified: true,
        anonymous: false,
        created_at: new Date(Date.now() - 1800000).toISOString(),
        updated_at: new Date(Date.now() - 1800000).toISOString(),
    },
    {
        id: '5',
        user_id: 'user5',
        type: 'violence',
        severity: 'high',
        title: 'Street Fight in Surulere',
        description: 'Violent altercation between groups',
        latitude: 6.4969,
        longitude: 3.3584,
        address: 'Surulere, Lagos',
        verified: true,
        anonymous: false,
        created_at: new Date(Date.now() - 5400000).toISOString(),
        updated_at: new Date(Date.now() - 5400000).toISOString(),
    },
    {
        id: '6',
        user_id: 'user6',
        type: 'harassment',
        severity: 'medium',
        title: 'Police Harassment at Checkpoint',
        description: 'Extortion and harassment reported at checkpoint',
        latitude: 6.5878,
        longitude: 3.3214,
        address: 'Ikeja, Lagos',
        verified: false,
        anonymous: true,
        created_at: new Date(Date.now() - 10800000).toISOString(),
        updated_at: new Date(Date.now() - 10800000).toISOString(),
    },
    {
        id: '7',
        user_id: 'user7',
        type: 'robbery',
        severity: 'medium',
        title: 'Bag Snatching in Yaba',
        description: 'Phone and bag snatched by motorcyclist',
        latitude: 6.5148,
        longitude: 3.3711,
        address: 'Yaba, Lagos',
        verified: true,
        anonymous: false,
        created_at: new Date(Date.now() - 14400000).toISOString(),
        updated_at: new Date(Date.now() - 14400000).toISOString(),
    },
    {
        id: '8',
        user_id: 'user8',
        type: 'accident',
        severity: 'low',
        title: 'Minor Accident in Ikoyi',
        description: 'Fender bender, no injuries',
        latitude: 6.4541,
        longitude: 3.4316,
        address: 'Ikoyi, Lagos',
        verified: true,
        anonymous: false,
        created_at: new Date(Date.now() - 18000000).toISOString(),
        updated_at: new Date(Date.now() - 18000000).toISOString(),
    },
];

// Mock users for live tracking demo
export const mockLiveUsers: ({ user: User; location: UserLocation })[] = [
    {
        user: {
            id: '1',
            email: 'john.parent@example.com',
            role: 'parent',
            full_name: 'John Doe',
            phone: '+234 901 234 5678',
            subscription_tier: 'premium',
            location_sharing_enabled: true,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        location: {
            id: 'loc1',
            user_id: '1',
            latitude: 6.5244,
            longitude: 3.3792,
            accuracy: 10,
            updated_at: new Date().toISOString(),
        },
    },
    {
        user: {
            id: '2',
            email: 'mary.school@example.com',
            role: 'school_admin',
            full_name: 'Mary Johnson',
            phone: '+234 902 345 6789',
            subscription_tier: 'family',
            location_sharing_enabled: true,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        location: {
            id: 'loc2',
            user_id: '2',
            latitude: 6.4474,
            longitude: 3.4700,
            accuracy: 15,
            updated_at: new Date().toISOString(),
        },
    },
    {
        user: {
            id: '3',
            email: 'security@estate.com',
            role: 'security',
            full_name: 'Security Officer',
            phone: '+234 903 456 7890',
            subscription_tier: 'free',
            location_sharing_enabled: true,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        location: {
            id: 'loc3',
            user_id: '3',
            latitude: 6.4281,
            longitude: 3.4219,
            accuracy: 20,
            updated_at: new Date().toISOString(),
        },
    },
    {
        user: {
            id: '4',
            email: 'traveler@example.com',
            role: 'traveler',
            full_name: 'Sarah Williams',
            phone: '+234 904 567 8901',
            subscription_tier: 'premium',
            location_sharing_enabled: true,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        location: {
            id: 'loc4',
            user_id: '4',
            latitude: 6.5878,
            longitude: 3.3214,
            accuracy: 12,
            updated_at: new Date().toISOString(),
        },
    },
    {
        user: {
            id: '5',
            email: 'parent2@example.com',
            role: 'parent',
            full_name: 'David Brown',
            phone: '+234 905 678 9012',
            subscription_tier: 'family',
            location_sharing_enabled: true,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
        location: {
            id: 'loc5',
            user_id: '5',
            latitude: 6.4672,
            longitude: 3.5663,
            accuracy: 18,
            updated_at: new Date().toISOString(),
        },
    },
];

export const mockAllUsers: User[] = [
    ...mockLiveUsers.map(u => u.user),
    {
        id: '6',
        email: 'inactive@example.com',
        role: 'parent',
        full_name: 'Inactive User',
        phone: '+234 906 789 0123',
        subscription_tier: 'free',
        location_sharing_enabled: false,
        created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
        updated_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
    {
        id: '7',
        email: 'school2@example.com',
        role: 'school_admin',
        full_name: 'School Admin 2',
        phone: '+234 907 890 1234',
        subscription_tier: 'premium',
        location_sharing_enabled: false,
        created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
        updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
];
